Ans.1 import java.util.Scanner;
      public class gg {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int arr[] = new int[5];
		System.out.println("Enter the elements  of an array");
		
		try {
			for(int i=0;i<arr.length;i++)
			{
				arr[i] = sc.nextInt();
			}
			System.out.println(arr[6]);
		} catch (Exception e) {
			System.out.println(e);
		}
	  }
      }

Ans.2 import java.util.Scanner;
   public class gg {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int arr[] = new int[5];
		System.out.println("Enter the elements  of an array");
		
		try {
			for(int i=0;i<arr.length;i++)
			{
				arr[i] = sc.nextInt();
			}
			System.out.println("Enter the value of n: ");
			int n = sc.nextInt();
			System.out.println(arr[n]);
			int result = n/0;
			System.out.println(result);
		} 
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Enter the value of n below 5");
		}
		catch (ArithmeticException e) {
			System.out.println(e);
		}
		catch(Exception e)
		{
			System.out.println("Please enter integer value for n");
		}
	}
     }

Ans.3 public class Main {
    public static void main(String[] args) {
        throw new Error("This is an example Error.");
    }
}
This is the example of checked exception and will throw an exception at the time of compilation.

public class Main {
    public static void main(String[] args) {
        throw new RuntimeException("This is an example RuntimeException.");
    }
}
This is the example of runtime Exception and this code will be compiled.



Ans.4 import java.util.Arrays;
import java.util.Scanner;
public class rethrowing {
   public static void main(String [] args) {
	   Scanner sc = new Scanner(System.in);
	      int[] arr = {10, 20, 30, 2, 0, 8};
	      System.out.println("Array: "+Arrays.toString(arr));
	      System.out.println("select value of a and b from positions (0 to 5) of an array");
	      int a = sc.nextInt();
	      int b = sc.nextInt();
	      try {
	         int result = (arr[a])/(arr[b]);
	         System.out.println("Result : "+result);
	      }
	      catch(ArrayIndexOutOfBoundsException e) {
	         throw new IndexOutOfBoundsException();
	      }
	      catch(ArithmeticException e) {
	         throw new IndexOutOfBoundsException();
	      }
        }
   }

Ans.5 import java.util.Scanner;
      public class example {
	 public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		try {	
			System.out.println("Enter x: ");
			int x = sc.nextInt();
			
			System.out.println("Enter y: ");
			int y = sc.nextInt();
		
			int result = x / y;
			
			System.out.println("Result: "+  result);
			
		} catch (ArithmeticException e) {
			System.out.println("Arithmetic Exception");
		} catch (Exception e) {
			System.out.println("Value is not a 32 bit signed integer ");
		}
	}
   }
